// template/react/src/EventComponent.jsx
import React from "react";
import { receiveEvents, removeListener, sendEvents } from "../helpers/eventManager";

const EventComponent = () => {
  const [message, setMessage] = React.useState("");

  function handleClick() {
    const events = [
      {
        name: "reactMessage",
        detail: `Random number ${new Date().getTime() % 10}`,
      },
    ];
    sendEvents(events);
  }

  const listOfHandler = [
    {
      name: "vueMessage",
      handler: (event) => {
        setMessage(event.detail);
      },
    },
  ];

  React.useEffect(() => {
    receiveEvents(listOfHandler);
    return () => {
      removeListener(listOfHandler);
    };
  }, [message]);

  return (
    <div>
      {message ? <p>Message receive: {message}</p> : <p>Waiting for data...</p>}
      <button onClick={handleClick}>Send Event React</button>
    </div>
  );
};

export default EventComponent;

// template/vue/src/EventComponent.vue
<template>
  <div>
    <p v-if="message">Message receive: {{ message }}</p>
    <p v-else>Waiting for data...</p>
    <button @click="handleClick">Send Vue message</button>
  </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from "vue";
import {
  receiveEvents,
  removeListener,
  sendEvents,
} from "../helpers/eventManager";

const message = ref("");

function handleClick() {
  const events = [
    {
      name: "vueMessage",
      detail: `Random number ${new Date().getTime() % 10}`,
    },
  ];
  sendEvents(events);
}

const listOfHandler = [
  {
    name: "reactMessage",
    handler: (event) => {
      message.value = event.detail;
    },
  },
];

onMounted(() => {
  receiveEvents(listOfHandler);
});

onUnmounted(() => {
  removeListener(listOfHandler);
});
</script>
