// cli/mini_app_example/helpers/EmbededMicroFrontEnd.vue
<template>
  <div ref="remoteContainer"></div>
</template>

<script>
import { loadRemote } from "./loadRemoteModule";

export default {
  props: ['remoteUrl', 'scope', 'module'],
  async mounted() {
    loadRemote(this.$props.remoteUrl, this.$props.scope, this.$props.module)
    .then((remote) => {
      console.log("loadRemote then moute::", remote);
      remote.mount(this.$refs.remoteContainer);
    })
    .catch((err) => {
      console.error("Failed to load remote:", err);
    });
  },
};
</script>

// template/helpers/EmbededMicroFrontEnd.jsx
import React, { useRef, useEffect } from "react";
import { loadRemote } from "./loadRemoteModule";

function EmbededMicroFrontEnd({ remoteUrl, scope, module }) {
  const mountRef = useRef(null);
  useEffect(() => {
    loadRemote(remoteUrl, scope, module)
      .then((remote) => {
        console.log("loadRemote then moute::", remote);
        remote.mount(mountRef.current);
      })
      .catch((err) => {
        console.error("Failed to load remote:", err);
      });
    
  }, []);
  return <div ref={mountRef} />;
}

export default EmbededMicroFrontEnd;
