// template/react/src/EventComponent.jsx
import React from "react";
import { receiveEvents, removeListener, sendEvents } from "../helpers/eventManager";

/**
 * React component that demonstrates cross-framework communication using `CustomEvent`.
 * It listens for events from other microfrontends (Vue and Angular), and can dispatch events
 * to other frameworks.
 *
 * @component
 *
 * @example
 * // Inside a React app
 * <EventComponent />
 *
 * // Expected integration in other apps to send events:
 * window.dispatchEvent(new CustomEvent("vueMessage", { detail: "Hello from Vue!" }));
 * window.dispatchEvent(new CustomEvent("angularMessage", { detail: "Hello from Angular!" }));
 */
const EventComponent = () => {
  const [message, setMessage] = React.useState("");

  /**
   * Handles the click event by dispatching a `reactMessage` custom event with a random number.
   *
   * @function
   * @returns {void}
   */
  function handleClick() {
    const events = [
      {
        name: "reactMessage",
        detail: `Random number ${new Date().getTime() % 10}`,
      },
    ];
    sendEvents(events);
  }

  /**
   * Event handler list for receiving events from other apps.
   * Listens for events from Vue and Angular microfrontends.
   *
   * @type {Array<{ name: string, handler: (event: CustomEvent) => void }>}
   */
  const listOfHandler = [
    {
      name: "vueMessage",
      handler: (event) => {
        setMessage(`Vue: ${event.detail}`);
      },
    },
    {
      name: "angularMessage",
      handler: (event) => {
        setMessage(`Angular: ${event.detail}`);
      },
    },
  ];

  // Subscribe to incoming events on mount and clean up on unmount
  React.useEffect(() => {
    receiveEvents(listOfHandler);
    return () => {
      removeListener(listOfHandler);
    };
  }, [message]);

  return (
    <div>
      {message ? <p>Message receive: {message}</p> : <p>Waiting for data...</p>}
      <button onClick={handleClick}>Send Event React</button>
    </div>
  );
};

export default EventComponent;

// template/angular/projects/event-component/src/lib/event-component.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';

/**
 * Angular component that demonstrates cross-framework communication using `CustomEvent`.
 * It listens for events from other microfrontends (Vue and React), and can dispatch events
 * to other frameworks.
 *
 * @example
 * <lib-event-component></lib-event-component>
 *
 * // To send events from other apps:
 * window.dispatchEvent(new CustomEvent("vueMessage", { detail: "Hello from Vue!" }));
 * window.dispatchEvent(new CustomEvent("reactMessage", { detail: "Hello from React!" }));
 */
@Component({
  selector: 'lib-event-component',
  templateUrl: './event-component.component.html',
  styleUrls: ['./event-component.component.scss']
})
export class EventComponent implements OnInit, OnDestroy {
  message = '';

  // List of event listeners
  private listeners = [
    {
      name: 'vueMessage',
      handler: (event: CustomEvent) => {
        this.message = `Vue: ${event.detail}`;
      }
    },
    {
      name: 'reactMessage',
      handler: (event: CustomEvent) => {
        this.message = `React: ${event.detail}`;
      }
    }
  ];

  ngOnInit(): void {
    // Register listeners
    this.listeners.forEach(({ name, handler }) => {
      window.addEventListener(name, handler as EventListener);
    });
  }

  ngOnDestroy(): void {
    // Remove listeners
    this.listeners.forEach(({ name, handler }) => {
      window.removeEventListener(name, handler as EventListener);
    });
  }

  /**
   * Dispatches a custom event named 'angularMessage' with a random number as detail.
   */
  sendEvent(): void {
    const event = new CustomEvent('angularMessage', {
      detail: `Random number ${new Date().getTime() % 10}`
    });
    window.dispatchEvent(event);
  }
}

<div>
    <h1>{{ message }}</h1>
    <button (click)="sendEvent()">Send Event Angular</button>
</div>
